config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :posts do
  member do
    get "vote"
  end
end

  resources :contents do
  member do
    get "vote"
  end
end

  resources :feeds do
  member do
    get "vote"
  end
end

  resources :presenters do
  member do
    get "vote"
  end
end

  resources :subscriptions do
  member do
    get "vote"
  end
end

  resources :roles do
  member do
    get "vote"
  end
end

  resources :memberships do
  member do
    get "vote"
  end
end

  resources :ui_elements do
  member do
    get "vote"
  end
end

  resources :approvals do
  member do
    get "vote"
  end
end

  resources :meta do
  member do
    get "vote"
  end
end

  resources :networks do
  member do
    get "vote"
  end
end

  resources :friendships do
  member do
    get "vote"
  end
end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/approval.rb
class Approval < ActiveRecord::Base
  belongs_to :user
  belongs_to :friendship
  belongs_to :subscription
  belongs_to :membership
  has_one :user
  has_one :meta
  acts_as_votable 
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  belongs_to :presenter
  belongs_to :friendship
  has_many :meta
  has_many :presenters
  has_many :posts
  has_many :ui_elements
  acts_as_votable 
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :user
  belongs_to :network
  belongs_to :subscription
  has_many :posts
  has_many :networks
  has_many :subscriptions
  has_many :meta
  acts_as_votable 
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  has_one :user
  has_one :approval
  has_many :contents
  acts_as_votable 
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :network
  has_one :network
  has_one :approval
  acts_as_votable 
end

app/models/meta.rb
class Meta < ActiveRecord::Base
  belongs_to :content
  belongs_to :user
  belongs_to :approval
  belongs_to :post
  belongs_to :feed
  belongs_to :presenter
  belongs_to :friendship
  acts_as_votable 
end

app/models/metum.rb
class Metum < ActiveRecord::Base
  belongs_to :content
  belongs_to :user
  belongs_to :approval
  belongs_to :post
  belongs_to :feed
  belongs_to :presenter
  belongs_to :friendship
end

app/models/network.rb
class Network < ActiveRecord::Base
  belongs_to :user
  has_many :users
  has_many :feeds
  has_many :memberships
  acts_as_votable 
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :feed
  belongs_to :network
  has_many :contents
  has_many :presenters
  has_many :networks
  has_many :feeds
  has_many :meta
  acts_as_votable 
end

app/models/presenter.rb
class Presenter < ActiveRecord::Base
  belongs_to :user
  has_many :contents
  has_many :meta
  has_many :ui_elements
  acts_as_votable 
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
  has_one :user
  acts_as_votable 
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :feed
  has_one :feed
  has_one :approval
  acts_as_votable 
end

app/models/ui_element.rb
class UiElement < ActiveRecord::Base
  belongs_to :user
  belongs_to :presenter
  belongs_to :content
  has_one :presenter
  acts_as_votable 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  has_many :networks
  has_many :posts
  has_many :feeds
  belongs_to :friendship
  belongs_to :role
  belongs_to :presenter
  has_many :memberships
  has_many :presenters
  has_many :friendships
  has_many :subscriptions
  has_many :roles
  has_many :contents
  has_many :meta
  belongs_to :approval
  belongs_to :network
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
  acts_as_votable 
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_content, only: [:show, :edit, :update, :destroy, :vote]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)
    @content.user = current_user

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @content.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:user_id, :body, :post_id, :presenter_id, :friendship_id)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/meta_helper.rb
module MetaHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/contents/_form.html.haml
= form_for @content, :html => { :class => 'form-horizontal form-model' } do |f|
  .form-group
    = f.label :body, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_area :body, :class => 'text-field form-control'
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), |
        contents_path, :class => 'btn btn-default'                   |

app/views/contents/edit.html.haml
- model_class = Content
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Content
= render :partial => 'form'

app/views/contents/index.html.haml
- model_class = Content
.page-header
  %h1= t '.title', :default => Content
%table.table.table-striped
  %thead
    %tr
      %th ID
      %th= model_class.human_attribute_name(:body)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @contents.each do |content|
      %tr
        %td= content.id
        %td= content.body
        %td= l content.created_at, format: :long
        %td
          = link_to content_path(content), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do
            = glyph 'info-sign'
            = glyph 'pencil'
          = link_to content_path(content), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do
            = glyph 'remove'
= link_to t('.new', :default => t("helpers.links.new")), |
  new_content_path,                                      |
  :class => 'btn btn-primary'                            |

app/views/contents/new.html.haml
- model_class = Content
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Content
= render :partial => 'form'

app/views/contents/show.html.haml
- model_class = Content
.page-header
  %h1= t '.title', :default => Content
.fieldset
  %dl
    %dt.label.label-default= model_class.human_attribute_name(:body)
    %dd
      %pre.prettyprint= @content.body
.form-group
  = link_to t('.back', :default => t("helpers.links.back")), |
    contents_path, :class => 'btn btn-default'               |
  = link_to t('.edit', :default => t("helpers.links.edit")), |
    edit_content_path(@content), :class => 'btn btn-default' |
  = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
    content_path(@content),                                                                                      |
    :method => 'delete',                                                                                         |
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
    :class => 'btn btn-danger'                                                                                   |