config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :posts do
  member do
    get "vote"
  end
end

  resources :contents do
  member do
    get "vote"
  end
end

  resources :feeds do
  member do
    get "vote"
  end
end

  resources :presenters do
  member do
    get "vote"
  end
end

  resources :subscriptions do
  member do
    get "vote"
  end
end

  resources :roles do
  member do
    get "vote"
  end
end

  resources :memberships do
  member do
    get "vote"
  end
end

  resources :ui_elements do
  member do
    get "vote"
  end
end

  resources :approvals do
  member do
    get "vote"
  end
end

  resources :meta do
  member do
    get "vote"
  end
end

  resources :networks do
  member do
    get "vote"
  end
end

  resources :friendships do
  member do
    get "vote"
  end
end

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/approval.rb
class Approval < ActiveRecord::Base
  belongs_to :user
  belongs_to :friendship
  belongs_to :subscription
  belongs_to :membership
  has_one :user
  has_one :meta
  acts_as_votable 
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  belongs_to :presenter
  belongs_to :friendship
  has_many :meta
  has_many :presenters
  has_many :posts
  has_many :ui_elements
  acts_as_votable 
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :user
  belongs_to :network
  belongs_to :subscription
  has_many :posts
  has_many :networks
  has_many :subscriptions
  has_many :meta
  acts_as_votable 
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  has_one :user
  has_one :approval
  has_many :contents
  acts_as_votable 
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :network
  has_one :network
  has_one :approval
  acts_as_votable 
end

app/models/meta.rb
class Meta < ActiveRecord::Base
  belongs_to :content
  belongs_to :user
  belongs_to :approval
  belongs_to :post
  belongs_to :feed
  belongs_to :presenter
  belongs_to :friendship
  acts_as_votable 
end

app/models/metum.rb
class Metum < ActiveRecord::Base
  belongs_to :content
  belongs_to :user
  belongs_to :approval
  belongs_to :post
  belongs_to :feed
  belongs_to :presenter
  belongs_to :friendship
end

app/models/network.rb
class Network < ActiveRecord::Base
  belongs_to :user
  has_many :users
  has_many :feeds
  has_many :memberships
  acts_as_votable 
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :feed
  belongs_to :network
  has_many :contents
  has_many :presenters
  has_many :networks
  has_many :feeds
  has_many :meta
  acts_as_votable 
end

app/models/presenter.rb
class Presenter < ActiveRecord::Base
  belongs_to :user
  has_many :contents
  has_many :meta
  has_many :ui_elements
  acts_as_votable 
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
  has_one :user
  acts_as_votable 
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :feed
  has_one :feed
  has_one :approval
  acts_as_votable 
end

app/models/ui_element.rb
class UiElement < ActiveRecord::Base
  belongs_to :user
  belongs_to :presenter
  belongs_to :content
  has_one :presenter
  acts_as_votable 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  has_many :networks
  has_many :posts
  has_many :feeds
  belongs_to :friendship
  belongs_to :role
  belongs_to :presenter
  has_many :memberships
  has_many :presenters
  has_many :friendships
  has_many :subscriptions
  has_many :roles
  has_many :contents
  has_many :meta
  belongs_to :approval
  belongs_to :network
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
  acts_as_votable 
end

app/controllers/ui_elements_controller.rb
class UiElementsController < ApplicationController
  before_action :set_ui_element, only: [:show, :edit, :update, :destroy, :vote]

  # GET /ui_elements
  # GET /ui_elements.json
  def index
    @ui_elements = UiElement.all
  end

  # GET /ui_elements/1
  # GET /ui_elements/1.json
  def show
  end

  # GET /ui_elements/new
  def new
    @ui_element = UiElement.new
  end

  # GET /ui_elements/1/edit
  def edit
  end

  # POST /ui_elements
  # POST /ui_elements.json
  def create
    @ui_element = UiElement.new(ui_element_params)

    respond_to do |format|
      if @ui_element.save
        format.html { redirect_to @ui_element, notice: 'Ui element was successfully created.' }
        format.json { render :show, status: :created, location: @ui_element }
      else
        format.html { render :new }
        format.json { render json: @ui_element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ui_elements/1
  # PATCH/PUT /ui_elements/1.json
  def update
    respond_to do |format|
      if @ui_element.update(ui_element_params)
        format.html { redirect_to @ui_element, notice: 'Ui element was successfully updated.' }
        format.json { render :show, status: :ok, location: @ui_element }
      else
        format.html { render :edit }
        format.json { render json: @ui_element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ui_elements/1
  # DELETE /ui_elements/1.json
  def destroy
    @ui_element.destroy
    respond_to do |format|
      format.html { redirect_to ui_elements_url, notice: 'Ui element was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @ui_element.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ui_element
      @ui_element = UiElement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ui_element_params
      params.require(:ui_element).permit(:meta, :user_id, :presenter_id, :content_id)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meta_helper.rb
module MetaHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/ui_elements_helper.rb
module UiElementsHelper
end

app/views/ui_elements/_form.html.haml
= form_for @ui_element, :html => { :class => 'form-horizontal form-model' } do |f|
  .form-group
    = f.label :meta, :class => 'control-label col-md-2'
    .col-md-10
      = f.text_area :meta, :class => 'text-field form-control'
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), |
        ui_elements_path, :class => 'btn btn-default'                |

app/views/ui_elements/edit.html.haml
- model_class = UIElement
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => UIElement
= render :partial => 'form'

app/views/ui_elements/index.html.haml
- model_class = UIElement
.page-header
  %h1= t '.title', :default => UIElement
%table.table.table-striped
  %thead
    %tr
      %th ID
      %th= model_class.human_attribute_name(:meta)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @ui_elements.each do |ui_element|
      %tr
        %td= ui_element.id
        %td= ui_element.meta
        %td= l ui_element.created_at, format: :long
        %td
          = link_to ui_element_path(ui_element), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do
            = glyph 'info-sign'
            = glyph 'pencil'
          = link_to ui_element_path(ui_element), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do
            = glyph 'remove'
= link_to t('.new', :default => t("helpers.links.new")), |
  new_ui_element_path,                                   |
  :class => 'btn btn-primary'                            |

app/views/ui_elements/new.html.haml
- model_class = UIElement
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => UIElement
= render :partial => 'form'

app/views/ui_elements/show.html.haml
- model_class = UIElement
.page-header
  %h1= t '.title', :default => UIElement
.fieldset
  %dl
    %dt.label.label-default= model_class.human_attribute_name(:meta)
    %dd
      %pre.prettyprint= @ui_element.meta
.form-group
  = link_to t('.back', :default => t("helpers.links.back")), |
    ui_elements_path, :class => 'btn btn-default'            |
  = link_to t('.edit', :default => t("helpers.links.edit")),       |
    edit_ui_element_path(@ui_element), :class => 'btn btn-default' |
  = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
    ui_element_path(@ui_element),                                                                                |
    :method => 'delete',                                                                                         |
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
    :class => 'btn btn-danger'                                                                                   |